// Generated by Bison
#include "json.tab.h"
#include "helper.c"
#include "json_util.h"
#include<stdio.h>
#include<stdlib.h>
#include <unistd.h>

/*
A simple (a.k.a. incomplete) JSON validator.
Made as an example to show how to use flex and bison.
*/

int yylex();
extern char* yytext;
char s[100];
shell_init();

int main(int argc, char *argv[]) {
	// Just calls yyparse.
	// Obviously, you might want to do something more complex here.
	while(1) {
		//printPrompt();
		switch(yyparse()) {
			case 0: if (processCommand() == 1) {
						printf("Successfully exited shell");
						break;
					};
			case 1: fprintf(stderr, "%s\n", s);
					break;
			default: break;
		}
	}
	return 0;
}

/*
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__79rhkp1fndgsc:/mnt/c/Program Files (x86)/VMware/VMware Workstation/bin/:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/juanf/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/juanf/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/juanf/.dotnet/tools:/mnt/c/Users/juanf/AppData/Local/Programs/Julia 1.5.3/bin:/snap/bin */